# Generated by Django 3.2.6 on 2024-07-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_mukadam',
            new_name='Mukadam',
        ),
    ]
