# Generated by Django 3.2.6 on 2024-07-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_add_mukadam_mukadam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karkhana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Taneg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taneg', models.FloatField()),
                ('date', models.DateField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('mukadam', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='owner.mukadam')),
            ],
        ),
    ]
