# Generated by Django 3.2.6 on 2024-07-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_karkhana_taneg'),
    ]

    operations = [
        migrations.AddField(
            model_name='taneg',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taneg',
            name='karkhana',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='owner.karkhana'),
        ),
    ]
