# Generated by Django 5.0.6 on 2024-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20240706_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('status', models.IntegerField(max_length=100)),
            ],
        ),
    ]
