# Generated by Django 5.0.6 on 2024-07-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_taneg_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taneg',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.vehicle'),
        ),
    ]
