# Generated by Django 5.0.6 on 2024-07-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_taneg_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mobile',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pin',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
