# Generated by Django 5.0.6 on 2024-11-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_vehicle_mobile_vehicle_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mukadam',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pin',
        ),
    ]
